### ISSUE TITLE
Terminal becomes unresponsive when hitting backspace 'too much' and crashes in vim

### ISSUE THREAD

**Issue by exp0nge** [c9/c9.ide.terminal.monitor#4]
When the backspace is hit a few many too much, the terminal becomes unresponsive. Secondly, the terminal will often crash when opening vim with it using `vi some-file.txt`

**Comment by nightwing** [comment]
Do you see this on sdk version or on c9.io? On which browser/OS?

>  Secondly, the terminal will often crash when opening vim with it using vi some-file.txt

How does it crash?

**Comment by exp0nge** [comment]
I'm using c9.io on Chrome, Windows. With `vi`, I think it's the same issue as with the terminal freezing up. I notice this when I edit hidden files like `.gitignore`.

**Comment by nightwing** [comment]
Which keyboard layout do you use?

**Comment by exp0nge** [comment]
The default one, I've only really changed the theme.

**Comment by nightwing** [comment]
I mean the windows keyboard layout, english us or something else?

Does it resume working if you press ctrl-c or ctrl-d?

**Comment by exp0nge** [comment]
English. I pretty much just open a new terminal and dispose of the unresponsive one since it doesn't respond to my key presses.

**Comment by nightwing** [comment]
could you please email support@c9.io to send your username and workspace name where you see this issue.

**Comment by exp0nge** [comment]
I'll send a support ticket if it happens again. I'll close the issue for now.
